import Dexie, { type Table } from 'dexie'

// ─── Type definitions for each table ───────────────────────────────

/**
 * Meta is a simple key-value table for app configuration.
 * We store things like the PBKDF2 salt, the encrypted verification token,
 * the user's lock behavior preference, and whether setup is complete.
 *
 * The `key` field is the primary key (e.g., "salt", "setupComplete").
 * The `value` field holds whatever data that key needs — could be a
 * Uint8Array (salt), a string (verification token), or a boolean.
 */
export interface MetaEntry {
  key: string
  value: unknown
}

/**
 * A password vault entry. Every sensitive field (siteName, username, password)
 * is stored as an encrypted string — meaning what's actually in IndexedDB is
 * base64-encoded ciphertext, not the plaintext.
 *
 * dateAdded/dateModified are Unix timestamps (milliseconds) so we can sort.
 */
export interface PasswordEntry {
  id?: number            // Auto-generated by Dexie (++id)
  siteName: string       // Encrypted
  siteUrl?: string       // Encrypted (optional — link to the site)
  username: string       // Encrypted
  password: string       // Encrypted
  dateAdded: number      // Timestamp (ms)
  dateModified: number   // Timestamp (ms)
}

/**
 * A note category (e.g., "Personal", "School").
 *
 * `name` is encrypted because category names could reveal info about the user.
 * `color` is NOT encrypted — it's just a CSS identifier like "blue" or "rose"
 * and contains no sensitive data. We need it unencrypted so we can render
 * colored category chips before the user unlocks the app... actually no,
 * categories only show after unlock. But the spec says color stays unencrypted
 * to keep things simple — there's no security value in encrypting "blue".
 *
 * `order` lets the user reorder categories in the UI.
 */
export interface NoteCategoryEntry {
  id?: number
  name: string          // Encrypted
  color: string         // NOT encrypted (e.g., "blue", "rose", "amber")
  order: number         // Display order
  dateAdded: number
}

/**
 * A secure note. Like passwords, title and content are encrypted.
 *
 * `categoryId` is a foreign key pointing to noteCategories.id.
 * It's optional — uncategorized notes are allowed. We don't encrypt this
 * because it's just a number referencing another row; by itself it reveals
 * nothing (you'd need to decrypt the category name to know what it means).
 */
export interface NoteEntry {
  id?: number
  categoryId?: number   // FK → noteCategories.id (nullable)
  title: string         // Encrypted
  content: string       // Encrypted
  order?: number        // Display order for manual sort mode (Phase 8)
  dateAdded: number
  dateModified: number
}

// ─── Database class ────────────────────────────────────────────────

/**
 * ConstrictorDB extends Dexie to define our schema.
 *
 * The schema string passed to stores() defines INDEXES, not columns.
 * For example, "++id, siteName" means:
 *   - `id` is an auto-incrementing primary key
 *   - `siteName` is indexed (so we could query by it, though with encrypted
 *     data the index isn't useful for searching — we decrypt in memory)
 *
 * You can store any other properties on the object; they just won't be indexed.
 * We index fields like dateAdded/dateModified so Dexie can sort by them
 * efficiently at the database level.
 */
class ConstrictorDB extends Dexie {
  meta!: Table<MetaEntry, string>
  passwords!: Table<PasswordEntry, number>
  noteCategories!: Table<NoteCategoryEntry, number>
  notes!: Table<NoteEntry, number>

  constructor() {
    super('constrictor')

    // Version 1 — our initial schema.
    // If we ever need to add tables or fields later, we add a new version()
    // block with an upgrade function — Dexie handles the migration.
    this.version(1).stores({
      meta: 'key',
      passwords: '++id, siteName, dateModified',
      noteCategories: '++id, color, order',
      notes: '++id, categoryId, dateModified',
    })

    // Version 2 — Phase 8: add `order` index on notes for manual sort mode.
    // The `order` field enables user-defined note ordering via drag-and-drop.
    // Dexie handles this automatically — existing rows get `order: undefined`
    // until the user switches to manual mode, at which point we assign values.
    this.version(2).stores({
      meta: 'key',
      passwords: '++id, siteName, dateModified',
      noteCategories: '++id, color, order',
      notes: '++id, categoryId, dateModified, order',
    })

    // Version 3 — add optional siteUrl field to passwords.
    // Existing rows will have siteUrl: undefined until the user adds a URL.
    // No index needed — siteUrl is not searched or sorted by.
    this.version(3).stores({
      meta: 'key',
      passwords: '++id, siteName, dateModified',
      noteCategories: '++id, color, order',
      notes: '++id, categoryId, dateModified, order',
    })
  }
}

// ─── Singleton instance ────────────────────────────────────────────

/**
 * We export a single database instance. Every part of the app imports
 * this same `db` object. Dexie handles the IndexedDB connection lifecycle
 * automatically — it opens the connection on first use and keeps it alive.
 */
export const db = new ConstrictorDB()
